#!/bin/bash

target=$1
rev=4.1
kver="$(make kernelversion)-watter-$rev-rpi-2712"

function usage()
{
	echo "Pick one of: apollo" 1>&2
	exit 1
}

case "$1" in
apollo)
	export KDEB_PACKAGEEXT=apollo
	export KBUILD_IMAGE=arch/arm64/boot/Image.gz
	;;
*)
	usage
esac

case "$1" in
*)
	image=bindeb-pkg
	export KDEB_CHANGELOG_DIST=stable
	export KDEB_SOURCENAME=linux-watter
	export KDEB_PKGVERSION=$kver
	export EMAIL="bcollins@watter.com"
	export NAME="Ben Collins"
	;;
esac

cpus=$(getconf _NPROCESSORS_ONLN)
nway=$(echo "($cpus * 15) / 10" | bc)
dir=${BUILD_DIR:-$(pwd)/build-${target}}

export HOSTCC=gcc
export CC=gcc

export MAKEFLAGS="O=$dir -j$nway KERNELRELEASE=$kver"

if ! test -f "$dir/.config"; then
	test -d "$dir" || mkdir "$dir"
	cp "watter-configs/$target" "$dir/.config"
fi

make $image
